# ========================= VERSION ========================
version: "3.9"

# ========================= SERVICES =======================
services:
  # ========================== API =========================
  prometeo-api:
    image: prometeo/prometeo-api-production:1.0.0
    container_name: prometeo-api-production
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: >
      sh -c "gunicorn -c /usr/src/app/server/gunicorn_conf.py server.wsgi:application"
    restart: always
    env_file:
      - ./src/config/.env
    links:
      - prometeo-database
    depends_on:
      prometeo-database:
        condition: service_healthy
    ports:
      - 9099:9099
    networks:
      - prometeo-network
  # ========================== API =========================
  # ======================= POSTGRESQL DB ==================
  prometeo-database:
    container_name: prometeo-database
    image: postgres:11-alpine
    restart: always
    env_file:
      - ./src/config/.env
    ports:
      - 5432:5432
    volumes:
      - prometeo-database:/var/lib/postgresql/data
    networks:
      - prometeo-network
    healthcheck:
      # We use `$$` here because:
      # one `$` goes to shell,
      # one `$` goes to `docker-compose.yml` escaping
      test: pg_isready -U $$POSTGRES_USER -h prometeo-database -p 5432 -d $$POSTGRES_DB -q
      interval: 10s
      timeout: 5s
      retries: 5
  # ======================= POSTGRESQL DB ==================

# ========================= VOLUMES ========================
volumes:
  prometeo-database: {}

# ========================= NETWORKS =======================
networks:
  # Network for your internals, use it by default
  prometeo-network:
    name: prometeo-network
    driver: bridge
