# -- Project information --
site_name: 'Documentation for Prometeo'
site_description: 'Documentación del proyecto API Prometeo usando mkdocs'
site_author: 'Alexei Diaz'
site_url: 'https://prometeoapi.com/'


# -- Repository --
repo_name: 'dsotoalexei/prometeo-ob'
repo_url: 'https://github.com/dsotoalexei/prometeo-ob'


# -- Copyright --
copyright: Derechos de autor &copy; 2022 <a href="https://prometeoapi.com/">Equipo de Prometeo</a>, Mantenido por el equipo de Prometeo.


# -- Configuration --
docs_dir: 'docs'
site_dir: 'static/docs/'

theme:
  name: 'material'
  language: 'es'
  features:
    - tabs
    - instant
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico

# -- Customization --
extra:
  search:
    language: 'es'
  version:
    provider: mike

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list

# -- Google Analytics --
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'


# -- Navigations --
nav:
  - Introducción: 'index.md'
  - Acerca de:
    - Contribución: about/contributing.md
    - Licencia: about/license.md


# -- Plugins --
plugins:
  - search:
      min_search_length: 4
